camera/horizontal_fov: 80.0
camera/vertical_fov: 55.0

raycast/dr:     0.1
raycast/dphi:   10
raycast/dtheta: 10

system/bbx/r: 0.75
system/bbx/overshoot: 0.25

aep/gain/r_min: 0
aep/gain/r_max: 5
aep/gain/zero: 0.5 # 25
aep/gain/lambda: 0.75
aep/gain/sigma_thresh: 0.2
aep/tree/extension_range: 1
aep/tree/max_sampling_radius: 10
aep/tree/initial_iterations: 15
aep/tree/cutoff_iterations: 30

rrt/min_nodes: 100

# bounding box: necessary to limit the simulation
# scenario (smaller than actual gazebo scenario)
# needs ~2m extra compared to Ours or RRT-IPP

# Small House
#boundary/min: [-6.0, -11.0, 0.0]
#boundary/max: [ 6.0,  9.0, 8.0]

# City Building
#boundary/min: [-10, -11.0, -0.1]
#boundary/max: [11.0, 10.0, 12.0]

# Bridge
#boundary/min: [-23, -6.0, 6.0]
#boundary/max: [23.0, 6.0, 25.0]

# Temple
#boundary/min: [-10.0, -20.0, 0.0]
#boundary/max: [10.0, 10.0, 14.0]

visualize_rays: false
visualize_tree: true
visualize_exploration_area: true

robot_frame: "firefly/base_link"
world_frame: "world"
